### ISSUE TITLE
No cachix entry for updated PHP 7.3

### ISSUE THREAD

**Issue by DanielSiepmann** [fossar/nix-phps#235] opened 2023-05-22 08:38 UTC
PHP 7.3 got updated last week: https://github.com/fossar/nix-phps/pull/233
But there is no cache entry at https://app.cachix.org/cache/fossar yet.

I guess the issue is mentioned here: https://github.com/fossar/nix-phps/actions/runs/4991609159/jobs/8938623799#step:33:3
>   Pushing is disabled as signingKey nor authToken are set (or are empty?) in your YAML file.

The job is still marked as success.

Would be cool if that could be fixed, so one doesn't need to compile PHP 7.3 locally.

**Comment by drupol** [comment] 2023-05-22 08:47
Weird, `authToken` is set: https://github.com/fossar/nix-phps/blob/master/.github/workflows/build.yaml#L37

@jtojnar Since you're the admin of this project, can you check if the env `CACHIX_AUTH_TOKEN` is still valid ?

**Comment by jtojnar** [comment] 2023-05-22 12:17
That is probably because the CI run is not in this repo. But weirdly, there are no runs in https://github.com/fossar/nix-phps/commits/master since October :eyes:

**Comment by DanielSiepmann** [comment] 2023-05-22 12:20
@jtojnar I guess because Build is only executed on Pull Request: https://github.com/fossar/nix-phps/blob/master/.github/workflows/build.yaml#L7 Which was / is fine as long as they are created from within the repo, as they would run within the repo.
I guess PRs since October where run from foreign repos.

Maybe add a trigger for main branch instead of PR? But I'm not an GitHub Actions Expert.

**Comment by jtojnar** [comment] 2023-05-22 12:24
Yeah, that would explain why the action link is missing since we are doing rebase-merges to have a clean history while GitHub does not support fast forward merges.

I think the issue is just that PHP 7.3 has been updated in a third party repo so the secrets are not there and `flake.lock` has not been updated yet.

**Comment by drupol** [comment] 2023-05-22 12:44
Issue should be fixed and should no happen anymore in the future.

Let me know if this is not the case.

Thx

**Closed** 2023-05-22 12:43 UTC
