### ISSUE TITLE
error: attribute 'php83' missing

### ISSUE THREAD

**Issue by jalbstmeijer** [fossar/nix-phps#276] opened 2023-07-14 10:35 UTC
Hi,

Just doing my first steps in NixOS.
I can install any php version except for php83.

I'm I missing something?

```
error: attribute 'php83' missing

          231|       group = config.services.caddy.group;
          232|       phpPackage = phps.packages.${builtins.currentSystem}.php83;
             |                    ^
          233|       settings = {
       Did you mean one of php73, php80, php81, php82 or php?
```

Gr, Justin

**Comment by drupol** [comment] 2023-07-14 10:36
Hi !

Could you try to run `nix flake update` and retry again ?

**Comment by jalbstmeijer** [comment] 2023-07-14 10:38
The same;

```
# nix flake update
warning: updating lock file '/root/flakes/flake.lock':
• Updated input 'phps':
    'github:fossar/nix-phps/599d3e0f67ad649402b0b553f58561436c070794' (2023-07-13)
  → 'github:fossar/nix-phps/3499510c674f2b7182c5e444f0cefed304b4f75a' (2023-07-13)

# nixos-rebuild switch --flake .#xxx
building the system configuration...
error: attribute 'php83' missing

       at /nix/store/xxx

          231|       group = config.services.caddy.group;
          232|       phpPackage = phps.packages.${builtins.currentSystem}.php83;
             |                    ^
          233|       settings = {
       Did you mean one of php73, php80, php81, php82 or php?
(use '--show-trace' to show detailed location information)

```

**Comment by drupol** [comment] 2023-07-14 10:41
Ok, thanks.

Could you share your nix file ? so I can see how `phps` is being built.

**Comment by jalbstmeijer** [comment] 2023-07-14 10:56
Ah, yes would not be surprised if that is it. I might be locked in to a repo rev.

I had a hard time figuring out how to get to nix-phps work in my NixOS config and eventually copy/pasted this from https://discourse.nixos.org/t/installing-old-php-version-on-nixos/25693/5

'''
let
  # using pkgs2 to avoid recursive loop with fetchFromGitHub
  # see https://stackoverflow.com/questions/73097604/nixos-how-to-import-some-configuration-from-gitlab-infinite-recursion-encounte
  pkgs2 = (import <nixpkgs> { });
  nix-phps = pkgs2.fetchFromGitHub {
    owner = "fossar";
    repo = "nix-phps";
    rev = "ac2bb3d416a10fc66d0148dddc63a19c6c5a907c";
    hash = "sha256-74kQIFf3Cu1aeOsohCiLuA1aXNGYt2U9tTUP0yvm4EA=";
  };
  phps = import nix-phps;
in
```

**Comment by drupol** [comment] 2023-07-14 11:02
Right, the problem is easy. It comes from the line `rev = "ac2bb3d416a10fc66d0148dddc63a19c6c5a907c";`. Basically, this is locking the version of `nix-phps` to that particular commit where `php83` didn't existed yet.

If you're using a flake, you should actually remove the call `pkg2.fetchFromGitHub {...}`.

Once it's done, add a new `input` to your flake:

`    nix-phps.url = "github:fossar/nix-phps";`

You can see an example here: https://github.com/loophp/nix-shell/blob/master/flake.nix

By adding an input to your flake, the file `flake.lock` will take care of updating your inputs when you do `nix flake update`.

Hope it's clear, let me know how it goes.

**Comment by jalbstmeijer** [comment] 2023-07-14 11:22
Yes, already had a 

```
    phps.url = "github:fossar/nix-phps";
```

But still struggling how to reference to these packages. The  example does  not make it clearer for me.

Without the ```pkg2.fetchFromGitHub {...}.``` I get now;

```
error: undefined variable 'phps'

       at xxx:

           62|       group = config.services.caddy.group;
           63|       phpPackage = phps.packages.${builtins.currentSystem}.php83;
             |                    ^
           64|       settings = {

```
 

```
  services.phpfpm.pools = {
    "www.website.com" = {
      user = config.services.caddy.user;
      group = config.services.caddy.group;
      phpPackage = phps.packages.${builtins.currentSystem}.php83;
      settings = {
         ....
      };
    };
  };

```

**Comment by drupol** [comment] 2023-07-14 11:24
Then I would suggest to use an overlay, let me get back on the computer to show you in 10 min.

**Comment by drupol** [comment] 2023-07-14 11:34
Here's how to create `pkgs2` containing what you need:

```nix
pkgsWithNixPhps = import nixpkgs {
  overlays = [inputs.nix-phps.overlays.default];
  inherit system;
  config.allowUnfree = true;
};
```

**Comment by jalbstmeijer** [comment] 2023-07-14 13:25
@drupol, thank you very much for your feedback!

Especially as the issue is my inexperience with NixOS, its literary my first day on it. 

So although your feedback is probably exactly what I need, it stays a mystery to me.
Tried different ways, but end up not getting it to work.

If you still want to help me out, let me know what the most effective way would be, otherwise I'll just struggle on

**Comment by drupol** [comment] 2023-07-14 16:43
I can help further, but then I would need to have your nix file so I can reproduce the issue and provide the fix for you.

**Comment by jalbstmeijer** [comment] 2023-07-14 17:17
Ok, here the basics, which now should work. Bit stuck at an older source git rev. Therefore not working when choosing php83.

flake.nix
```
{
  description = "NixOS configuration with two or more channels";
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.05";
    nixpkgs-unstable.url = "nixpkgs/nixos-unstable";
    phps.url = "github:fossar/nix-phps";
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, phps }:
    let
      system = "x86_64-linux";
      overlay-unstable = final: prev: {
        unstable = nixpkgs-unstable.legacyPackages.${prev.system};
      };
    in {
      nixosConfigurations."testphps" = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          ({ config, pkgs, ... }: { nixpkgs.overlays = [ overlay-unstable ]; })
          ./configuration.nix
          ./fossar.nix
        ];
      };

      devShell.x86_64-linux = nixpkgs.legacyPackages.x86_64-linux.mkShell {
        buildInputs = [
          phps.packages.x86_64-linux.php
        ];
      };
    };
}
```
configuration.nix
```
#{ config, pkgs, ... }:
{ modulesPath, config, pkgs, lib, ... }:
let
  # https://discourse.nixos.org/t/installing-old-php-version-on-nixos/25693/5
  # using pkgs2 to avoid recursive loop with fetchFromGitHub
  # see https://stackoverflow.com/questions/73097604/nixos-how-to-import-some-configuration-from-gitlab-infinite-recursion-encounte
  pkgs2 = (import <nixpkgs> { });
  nix-phps = pkgs2.fetchFromGitHub {
    owner = "fossar";
    repo = "nix-phps";
    rev = "ac2bb3d416a10fc66d0148dddc63a19c6c5a907c";
    hash = "sha256-74kQIFf3Cu1aeOsohCiLuA1aXNGYt2U9tTUP0yvm4EA=";
  };
  phps = import nix-phps;
in
{
  #imports = [ ./hardware.nix ];
  nixpkgs.config.allowUnfree = true; 
  system.stateVersion = "23.05";
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  environment.systemPackages = [ pkgs.vim pkgs.cachix ];

  services.phpfpm.pools = {
    "www.website1.com" = {
      user = config.services.caddy.user;
      group = config.services.caddy.group;
      phpPackage = phps.packages.${builtins.currentSystem}.php56;
      settings = {
        "listen.owner" = config.services.caddy.user;
        "pm" = "dynamic";
        "pm.max_children" = 75;
        "pm.start_servers" = 1;
        "pm.min_spare_servers" = 1;
        "pm.max_spare_servers" = 20;
        "pm.max_requests" = 500;
      };
    };
  };

  services.caddy.enable = true;
  services.caddy.virtualHosts."http://www.website1.com:8000" = {
    extraConfig = ''
      root * /var/www
      php_fastcgi unix/${config.services.phpfpm.pools."www.website1.com".socket}
      file_server
      log {
           output file /var/log/caddy/www.website1.com.log
      }
    '';
  };

}
```

**Comment by drupol** [comment] 2023-07-14 17:32
I modified the `flake.nix`, I can have `php83` in a shell with it:

```nix
{
  description = "NixOS configuration with two or more channels";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.05";
    nixpkgs-unstable.url = "nixpkgs/nixos-unstable";
    phps.url = "github:fossar/nix-phps";
  };
  outputs = { self, nixpkgs, nixpkgs-unstable, phps }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs-unstable {
        inherit system;
        overlays = [
          phps.overlays.default
        ];
      };
    in {
      nixosConfigurations."testphps" = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [];
      };

      devShell.x86_64-linux = nixpkgs.legacyPackages.x86_64-linux.mkShell {
        buildInputs = [
          pkgs.php83
        ];
      };
    };
}
```

Do: `nix develop .`

**Comment by jalbstmeijer** [comment] 2023-07-14 18:55
Got it to work without  the ```pkg2.fetchFromGitHub {...}.``` in my configuration.nix.
I passed the ```inputs``` to the configuration.nix, following the example at https://nixos.wiki/wiki/Flakes

"If you want to pass on the flake inputs to external configuration files, you can use the specialArgs attribute:"

**Comment by drupol** [comment] 2023-07-14 19:42
> But I was not looking for a way to run it in a shell.

Sure, but that was done as an example, to show you how to use the overlay !

Anyway, I'm glad you found out a way to use it, I'm going to close the issue, feel free to reopen if you feel that this is not done yet.

**Closed by drupol** 2023-07-14 19:42 UTC
Labels: question
